app = "bw-health"
primary_region = "cdg"

[build]
  builder = "heroku/builder:22"

[env]
  PORT = "8080"
  NODE_ENV = "production"
  LOG_LEVEL = "info"

# Variables d'environnement sensibles
[secrets]
  JWT_SECRET = ""  # À définir via fly secrets set JWT_SECRET=votre_clé

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "bw_health_data"
  destination = "/data" 