[build]
  base = "frontend"
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

# Redirection pour les pages spécifiques
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/day/*"
  to = "/day.html"
  status = 200

# Redirection par défaut pour le routage côté client
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers pour le cache et la sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=0, must-revalidate" 